# Generated by Django 4.2 on 2023-09-12 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Name', max_length=255, validators=[django.core.validators.RegexValidator(code='first_name', message="Must to be first character uppercase also don't add any spaces", regex='^[A-Z]{1}[a-z]{2,}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Name', max_length=255, validators=[django.core.validators.RegexValidator(code='last_name', message="Must to be first character uppercase also don't add any spaces", regex='^[A-Z]{1}[a-z]{2,}$')]),
            preserve_default=False,
        ),
    ]
